ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS email_domain VARCHAR(255),
  ADD COLUMN IF NOT EXISTS support_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS billing_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS invoice_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS notification_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS email_sending_status VARCHAR(32) NOT NULL DEFAULT 'demo';

ALTER TABLE email_outbox
  ADD COLUMN IF NOT EXISTS sender_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS reply_to_email VARCHAR(255),
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
